# Data Understanding

The objective of this notebook is to understand the dataset before performing any preprocessing or machine learning.

# AI-Powered Retail Business Analytics & Forecasting Platform

# Phase 2: Data Understanding

## Objective

The objective of this notebook is to understand the structure, quality, and characteristics of the raw datasets before performing any preprocessing or analysis.

This phase focuses on:

- Loading all datasets
- Understanding dataset dimensions
- Exploring column information
- Identifying missing values
- Detecting duplicate records
- Understanding relationships among datasets
- Creating a data dictionary

In [1]:
!pip install plotly

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: plotly in C:\Users\rames\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (6.9.0)
Requirement already satisfied: narwhals>=1.15.1 in C:\Users\rames\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from plotly) (2.2.0)
Requirement already satisfied: packaging in C:\Users\rames\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from plotly) (25.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: C:\Users\rames\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", "{:.2f}".format)

In [3]:
customers = pd.read_csv("C:/Users/rames/notebook/DS-1/data/raw/olist_customers_dataset.csv")

geolocation = pd.read_csv("C:/Users/rames/notebook/DS-1/data/raw/olist_geolocation_dataset.csv")

order_items = pd.read_csv("C:/Users/rames/notebook/DS-1/data/raw/olist_order_items_dataset.csv")

payments = pd.read_csv("C:/Users/rames/notebook/DS-1/data/raw/olist_order_payments_dataset.csv")

reviews = pd.read_csv("C:/Users/rames/notebook/DS-1/data/raw/olist_order_reviews_dataset.csv")

orders = pd.read_csv("C:/Users/rames/notebook/DS-1/data/raw/olist_orders_dataset.csv")

products = pd.read_csv("C:/Users/rames/notebook/DS-1/data/raw/olist_products_dataset.csv")

sellers = pd.read_csv("C:/Users/rames/notebook/DS-1/data/raw/olist_sellers_dataset.csv")

translation = pd.read_csv("C:/Users/rames/notebook/DS-1/data/raw/product_category_name_translation.csv")

In [4]:
datasets = {

    "Customers": customers,

    "Geolocation": geolocation,

    "Orders": orders,

    "Order Items": order_items,

    "Payments": payments,

    "Reviews": reviews,

    "Products": products,

    "Sellers": sellers,

    "Category Translation": translation

}

In [5]:
summary = []

for name, df in datasets.items():

    summary.append({

        "Dataset": name,

        "Rows": df.shape[0],

        "Columns": df.shape[1],

        "Missing Values": df.isnull().sum().sum(),

        "Duplicate Rows": df.duplicated().sum()

    })

summary_df = pd.DataFrame(summary)

summary_df

                Dataset     Rows  Columns  Missing Values  Duplicate Rows
0             Customers    99441        5               0               0
1           Geolocation  1000163        5               0          261831
2                Orders    99441        8            4908               0
3           Order Items   112650        7               0               0
4              Payments   103886        5               0               0
5               Reviews   100000        7          146532               0
6              Products    32951        9            2448               0
7               Sellers     3095        4               0               0
8  Category Translation       71        2               0               0

In [6]:
for name, df in datasets.items():

    print("="*80)

    print(name)

    print("="*80)

    display(df.head())

    print()

    df.info()

    print("\n")

================================================================================
Customers
================================================================================

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB


================================================================================
Geolocation
================================================================================

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.55,-46.64,sao paulo,SP
1,1046,-23.55,-46.64,sao paulo,SP
2,1046,-23.55,-46.64,sao paulo,SP
3,1041,-23.54,-46.64,sao paulo,SP
4,1035,-23.54,-46.64,sao paulo,SP

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB


================================================================================
Orders
================================================================================

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB


================================================================================
Order Items
================================================================================

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB


================================================================================
Payments
================================================================================

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB


================================================================================
Reviews
================================================================================

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   review_id                100000 non-null  object
 1   order_id                 100000 non-null  object
 2   review_score             100000 non-null  int64
 3   review_comment_title     11715 non-null   object
 4   review_comment_message   41753 non-null   object
 5   review_creation_date     100000 non-null  object
 6   review_answer_timestamp  100000 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB


================================================================================
Products
================================================================================

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.00,287.00,1.00,225.00,16.00,10.00,14.00
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.00,276.00,1.00,1000.00,30.00,18.00,20.00
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.00,250.00,1.00,154.00,18.00,9.00,15.00
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.00,261.00,1.00,371.00,26.00,4.00,26.00
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.00,402.00,4.00,625.00,20.00,17.00,13.00

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB


================================================================================
Sellers
================================================================================

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB


================================================================================
Category Translation
================================================================================

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [12]:
for name, df in datasets.items():

    print("="*80)

    print(name)

    print("="*80)

    missing = (
    df.isnull()
      .sum()
      .sort_values(ascending=False)
)

missing = missing[missing > 0]

display(missing)

================================================================================
Customers
================================================================================
================================================================================
Geolocation
================================================================================
================================================================================
Orders
================================================================================
================================================================================
Order Items
================================================================================
================================================================================
Payments
================================================================================
================================================================================
Reviews
================================================================================
================================================================================
Products
================================================================================
================================================================================
Sellers
================================================================================
================================================================================
Category Translation
================================================================================

Series([], dtype: int64)

In [13]:
missing_percent = (

df.isnull().mean()*100

).round(2)

missing_percent = missing_percent[missing_percent>0]

display(missing_percent)

Series([], dtype: float64)

In [14]:
missing_summary=[]

for name,df in datasets.items():

    total=df.isnull().sum().sum()

    percent=round(
        total/(df.shape[0]*df.shape[1])*100,
        2
    )

    missing_summary.append({

        "Dataset":name,

        "Total Missing":total,

        "Missing %":percent

    })

missing_summary=pd.DataFrame(
    missing_summary
)

missing_summary

                Dataset  Total Missing  Missing %
0             Customers              0       0.00
1           Geolocation              0       0.00
2                Orders           4908       0.62
3           Order Items              0       0.00
4              Payments              0       0.00
5               Reviews         146532      20.93
6              Products           2448       0.83
7               Sellers              0       0.00
8  Category Translation              0       0.00

In [8]:
duplicate_summary = []

for name, df in datasets.items():

    duplicate_summary.append({

        "Dataset": name,

        "Duplicate Rows": df.duplicated().sum()

    })

pd.DataFrame(duplicate_summary)

                Dataset  Duplicate Rows
0             Customers               0
1           Geolocation          261831
2                Orders               0
3           Order Items               0
4              Payments               0
5               Reviews               0
6              Products               0
7               Sellers               0
8  Category Translation               0

In [15]:
for name,df in datasets.items():

    memory=df.memory_usage(deep=True).sum()/1024**2

    print(name)

    print("Memory:",round(memory,2),"MB")

Customers
Memory: 26.59 MB
Geolocation
Memory: 130.26 MB
Orders
Memory: 52.94 MB
Order Items
Memory: 35.99 MB
Payments
Memory: 16.23 MB
Reviews
Memory: 39.54 MB
Products
Memory: 6.3 MB
Sellers
Memory: 0.59 MB
Category Translation
Memory: 0.01 MB

In [9]:
for name, df in datasets.items():

    print("="*70)

    print(name)

    print("="*70)

    display(df.describe(include='all'))

======================================================================
Customers
======================================================================

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
count,99441,99441,99441.00,99441,99441
unique,99441,96096,NaN,4119,27
top,274fa6071e5e17fe303b9748641082c8,8d50f5eadf50201ccdcedfb9e2ac8455,NaN,sao paulo,SP
freq,1,17,NaN,15540,41746
mean,NaN,NaN,35137.47,NaN,NaN
std,NaN,NaN,29797.94,NaN,NaN
min,NaN,NaN,1003.00,NaN,NaN
25%,NaN,NaN,11347.00,NaN,NaN
50%,NaN,NaN,24416.00,NaN,NaN
75%,NaN,NaN,58900.00,NaN,NaN
max,NaN,NaN,99990.00,NaN,NaN

======================================================================
Geolocation
======================================================================

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
count,1000163.00,1000163.00,1000163.00,1000163,1000163
unique,NaN,NaN,NaN,8011,27
top,NaN,NaN,NaN,sao paulo,SP
freq,NaN,NaN,NaN,135800,404268
mean,36574.17,-21.18,-46.39,NaN,NaN
std,30549.34,5.72,4.27,NaN,NaN
min,1001.00,-36.61,-101.47,NaN,NaN
25%,11075.00,-23.60,-48.57,NaN,NaN
50%,26530.00,-22.92,-46.64,NaN,NaN
75%,63504.00,-19.98,-43.77,NaN,NaN
max,99990.00,45.07,121.11,NaN,NaN

======================================================================
Orders
======================================================================

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-08-02 12:05:26,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-08 19:36:48,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

======================================================================
Order Items
======================================================================

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
count,112650,112650.00,112650,112650,112650,112650.00,112650.00
unique,98666,NaN,32951,3095,93318,NaN,NaN
top,8272b63d03f5f79c56e9e4120aec44ef,NaN,aca2eb7d00ea1a7b8ebd4e68314663af,6560211a19b47992c3666cc44a7e94c0,2017-07-21 18:25:23,NaN,NaN
freq,21,NaN,527,2033,21,NaN,NaN
mean,NaN,1.20,NaN,NaN,NaN,120.65,19.99
std,NaN,0.71,NaN,NaN,NaN,183.63,15.81
min,NaN,1.00,NaN,NaN,NaN,0.85,0.00
25%,NaN,1.00,NaN,NaN,NaN,39.90,13.08
50%,NaN,1.00,NaN,NaN,NaN,74.99,16.26
75%,NaN,1.00,NaN,NaN,NaN,134.90,21.15
max,NaN,21.00,NaN,NaN,NaN,6735.00,409.68

======================================================================
Payments
======================================================================

,order_id,payment_sequential,payment_type,payment_installments,payment_value
count,103886,103886.00,103886,103886.00,103886.00
unique,99440,NaN,5,NaN,NaN
top,fa65dad1b0e818e3ccc5cb0e39231352,NaN,credit_card,NaN,NaN
freq,29,NaN,76795,NaN,NaN
mean,NaN,1.09,NaN,2.85,154.10
std,NaN,0.71,NaN,2.69,217.49
min,NaN,1.00,NaN,0.00,0.00
25%,NaN,1.00,NaN,1.00,56.79
50%,NaN,1.00,NaN,1.00,100.00
75%,NaN,1.00,NaN,4.00,171.84
max,NaN,29.00,NaN,24.00,13664.08

======================================================================
Reviews
======================================================================

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
count,100000,100000,100000.00,11715,41753,100000,100000
unique,99173,99441,NaN,4600,36921,637,99010
top,0c76e7a547a531e7bf9f0b99cba071c1,df56136b8031ecd28e200bb18e6ddb2e,NaN,Recomendo,Muito bom,2017-12-19 00:00:00,2017-06-15 23:21:05
freq,3,3,NaN,426,230,466,4
mean,NaN,NaN,4.07,NaN,NaN,NaN,NaN
std,NaN,NaN,1.36,NaN,NaN,NaN,NaN
min,NaN,NaN,1.00,NaN,NaN,NaN,NaN
25%,NaN,NaN,4.00,NaN,NaN,NaN,NaN
50%,NaN,NaN,5.00,NaN,NaN,NaN,NaN
75%,NaN,NaN,5.00,NaN,NaN,NaN,NaN
max,NaN,NaN,5.00,NaN,NaN,NaN,NaN

======================================================================
Products
======================================================================

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32951,32341,32341.00,32341.00,32341.00,32949.00,32949.00,32949.00,32949.00
unique,32951,73,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,106392145fca363410d287a815be6de4,cama_mesa_banho,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,3029,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,48.48,771.50,2.19,2276.47,30.82,16.94,23.20
std,NaN,NaN,10.25,635.12,1.74,4282.04,16.91,13.64,12.08
min,NaN,NaN,5.00,4.00,1.00,0.00,7.00,2.00,6.00
25%,NaN,NaN,42.00,339.00,1.00,300.00,18.00,8.00,15.00
50%,NaN,NaN,51.00,595.00,1.00,700.00,25.00,13.00,20.00
75%,NaN,NaN,57.00,972.00,3.00,1900.00,38.00,21.00,30.00
max,NaN,NaN,76.00,3992.00,20.00,40425.00,105.00,105.00,118.00

======================================================================
Sellers
======================================================================

,seller_id,seller_zip_code_prefix,seller_city,seller_state
count,3095,3095.00,3095,3095
unique,3095,NaN,611,23
top,9e25199f6ef7e7c347120ff175652c3b,NaN,sao paulo,SP
freq,1,NaN,694,1849
mean,NaN,32291.06,NaN,NaN
std,NaN,32713.45,NaN,NaN
min,NaN,1001.00,NaN,NaN
25%,NaN,7093.50,NaN,NaN
50%,NaN,14940.00,NaN,NaN
75%,NaN,64552.50,NaN,NaN
max,NaN,99730.00,NaN,NaN

======================================================================
Category Translation
======================================================================

       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

In [10]:
for name, df in datasets.items():

    print("="*80)

    print(name)

    print("="*80)

    display(df.dtypes)

================================================================================
Customers
================================================================================

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

================================================================================
Geolocation
================================================================================

geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

================================================================================
Orders
================================================================================

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

================================================================================
Order Items
================================================================================

order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

================================================================================
Payments
================================================================================

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

================================================================================
Reviews
================================================================================

review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

================================================================================
Products
================================================================================

product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

================================================================================
Sellers
================================================================================

seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

================================================================================
Category Translation
================================================================================

product_category_name            object
product_category_name_english    object
dtype: object

In [11]:
for name, df in datasets.items():

    print("="*80)

    print(name)

    print("="*80)

    display(df.describe(include="all"))

================================================================================
Customers
================================================================================

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
count,99441,99441,99441.00,99441,99441
unique,99441,96096,NaN,4119,27
top,274fa6071e5e17fe303b9748641082c8,8d50f5eadf50201ccdcedfb9e2ac8455,NaN,sao paulo,SP
freq,1,17,NaN,15540,41746
mean,NaN,NaN,35137.47,NaN,NaN
std,NaN,NaN,29797.94,NaN,NaN
min,NaN,NaN,1003.00,NaN,NaN
25%,NaN,NaN,11347.00,NaN,NaN
50%,NaN,NaN,24416.00,NaN,NaN
75%,NaN,NaN,58900.00,NaN,NaN
max,NaN,NaN,99990.00,NaN,NaN

================================================================================
Geolocation
================================================================================

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
count,1000163.00,1000163.00,1000163.00,1000163,1000163
unique,NaN,NaN,NaN,8011,27
top,NaN,NaN,NaN,sao paulo,SP
freq,NaN,NaN,NaN,135800,404268
mean,36574.17,-21.18,-46.39,NaN,NaN
std,30549.34,5.72,4.27,NaN,NaN
min,1001.00,-36.61,-101.47,NaN,NaN
25%,11075.00,-23.60,-48.57,NaN,NaN
50%,26530.00,-22.92,-46.64,NaN,NaN
75%,63504.00,-19.98,-43.77,NaN,NaN
max,99990.00,45.07,121.11,NaN,NaN

================================================================================
Orders
================================================================================

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-08-02 12:05:26,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-08 19:36:48,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

================================================================================
Order Items
================================================================================

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
count,112650,112650.00,112650,112650,112650,112650.00,112650.00
unique,98666,NaN,32951,3095,93318,NaN,NaN
top,8272b63d03f5f79c56e9e4120aec44ef,NaN,aca2eb7d00ea1a7b8ebd4e68314663af,6560211a19b47992c3666cc44a7e94c0,2017-07-21 18:25:23,NaN,NaN
freq,21,NaN,527,2033,21,NaN,NaN
mean,NaN,1.20,NaN,NaN,NaN,120.65,19.99
std,NaN,0.71,NaN,NaN,NaN,183.63,15.81
min,NaN,1.00,NaN,NaN,NaN,0.85,0.00
25%,NaN,1.00,NaN,NaN,NaN,39.90,13.08
50%,NaN,1.00,NaN,NaN,NaN,74.99,16.26
75%,NaN,1.00,NaN,NaN,NaN,134.90,21.15
max,NaN,21.00,NaN,NaN,NaN,6735.00,409.68

================================================================================
Payments
================================================================================

,order_id,payment_sequential,payment_type,payment_installments,payment_value
count,103886,103886.00,103886,103886.00,103886.00
unique,99440,NaN,5,NaN,NaN
top,fa65dad1b0e818e3ccc5cb0e39231352,NaN,credit_card,NaN,NaN
freq,29,NaN,76795,NaN,NaN
mean,NaN,1.09,NaN,2.85,154.10
std,NaN,0.71,NaN,2.69,217.49
min,NaN,1.00,NaN,0.00,0.00
25%,NaN,1.00,NaN,1.00,56.79
50%,NaN,1.00,NaN,1.00,100.00
75%,NaN,1.00,NaN,4.00,171.84
max,NaN,29.00,NaN,24.00,13664.08

================================================================================
Reviews
================================================================================

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
count,100000,100000,100000.00,11715,41753,100000,100000
unique,99173,99441,NaN,4600,36921,637,99010
top,0c76e7a547a531e7bf9f0b99cba071c1,df56136b8031ecd28e200bb18e6ddb2e,NaN,Recomendo,Muito bom,2017-12-19 00:00:00,2017-06-15 23:21:05
freq,3,3,NaN,426,230,466,4
mean,NaN,NaN,4.07,NaN,NaN,NaN,NaN
std,NaN,NaN,1.36,NaN,NaN,NaN,NaN
min,NaN,NaN,1.00,NaN,NaN,NaN,NaN
25%,NaN,NaN,4.00,NaN,NaN,NaN,NaN
50%,NaN,NaN,5.00,NaN,NaN,NaN,NaN
75%,NaN,NaN,5.00,NaN,NaN,NaN,NaN
max,NaN,NaN,5.00,NaN,NaN,NaN,NaN

================================================================================
Products
================================================================================

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32951,32341,32341.00,32341.00,32341.00,32949.00,32949.00,32949.00,32949.00
unique,32951,73,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,106392145fca363410d287a815be6de4,cama_mesa_banho,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,3029,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,48.48,771.50,2.19,2276.47,30.82,16.94,23.20
std,NaN,NaN,10.25,635.12,1.74,4282.04,16.91,13.64,12.08
min,NaN,NaN,5.00,4.00,1.00,0.00,7.00,2.00,6.00
25%,NaN,NaN,42.00,339.00,1.00,300.00,18.00,8.00,15.00
50%,NaN,NaN,51.00,595.00,1.00,700.00,25.00,13.00,20.00
75%,NaN,NaN,57.00,972.00,3.00,1900.00,38.00,21.00,30.00
max,NaN,NaN,76.00,3992.00,20.00,40425.00,105.00,105.00,118.00

================================================================================
Sellers
================================================================================

,seller_id,seller_zip_code_prefix,seller_city,seller_state
count,3095,3095.00,3095,3095
unique,3095,NaN,611,23
top,9e25199f6ef7e7c347120ff175652c3b,NaN,sao paulo,SP
freq,1,NaN,694,1849
mean,NaN,32291.06,NaN,NaN
std,NaN,32713.45,NaN,NaN
min,NaN,1001.00,NaN,NaN
25%,NaN,7093.50,NaN,NaN
50%,NaN,14940.00,NaN,NaN
75%,NaN,64552.50,NaN,NaN
max,NaN,99730.00,NaN,NaN

================================================================================
Category Translation
================================================================================

       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

# Dataset Relationships

Customers
    │
(customer_id)
    │
    ▼
Orders
(order_id)
    │
    ├──────────────┐
    ▼              ▼
Payments      Reviews
    │
    ▼
Order Items
(product_id)
    │
    ▼
Products

| Dataset     | Primary Key           | Purpose                          |
| ----------- | --------------------- | -------------------------------- |
| Customers   | customer_id           | Customer information             |
| Orders      | order_id              | Order details                    |
| Order Items | order_id              | Purchased products               |
| Products    | product_id            | Product information              |
| Payments    | order_id              | Payment details                  |
| Reviews     | review_id             | Customer reviews                 |
| Sellers     | seller_id             | Seller information               |
| Geolocation | zip_code_prefix       | Customer/Seller location         |
| Translation | product_category_name | Portuguese → English translation |

# Key Observations

- The Olist dataset consists of multiple relational tables.
- Orders act as the central table connecting customers, products, payments, and reviews.
- Some datasets contain missing values that require cleaning.
- Duplicate records exist in certain tables and need to be removed.
- Date columns must be converted to datetime format.
- Product category names are in Portuguese and require translation.

# Conclusion

The data understanding phase provided a comprehensive overview of the dataset structure and quality.

The next step is Data Cleaning, where each dataset will be cleaned individually by handling missing values, removing duplicates, correcting data types, and preparing the data for integration.